Repository Naruita/time-tabler, pull requests merged in 2020-05, with the labels that each got.

#5 Added code to launch application from link
  simpleSchedule/timed_link.py
Labels: enhancement

#7 Fixes #1
  schedule.txt
  simpleSchedule/deploy.py
  simpleSchedule/schedule.txt
  simpleSchedule/test_class_timetablemaker.py
  simpleSchedule/timed_link.py
  simpleSchedule/timetablemaker.py
Labels: bug, enhancement

#8 Fixes #2
  simpleSchedule/converting_timestamps.py
  simpleSchedule/deploy.py
  simpleSchedule/schedule.txt
  simpleSchedule/schedule_module_check.py
  simpleSchedule/timetablemaker.py
Labels: bug

#9 Fixes #3
  simpleSchedule/converting_timestamps.py
  simpleSchedule/schedule.txt
  simpleSchedule/schedule_module_check.py
  simpleSchedule/timed_link.py
  simpleSchedule/timetablemaker.py
Labels: bug, enhancement
